version: "3"
services:
  hub:
    image: selenium/hub:3.141.59
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome:3.141.59
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  firefox:
    image: selenium/node-firefox:3.141.59
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  selenium-tests:
    image: prajkamal/seleniumtests
    depends_on:
          - chrome
          - firefox
    environment:
          - HUB_HOST=hub
          - MODULE=searchPageTestNG.xml
          - BROWSER=firefox
    volumes:
          - ./testresults-docker:/usr/share/udemy/test-output
